name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Publish project for deployment
      run: dotnet publish -o ./build -c Production
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact-${{ github.run_number }}
        path: build/**/*
